# Generated by Django 4.2 on 2024-12-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_appointment_appointmentabl'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentabl',
            name='Action',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
